### ISSUE TITLE
Design new angled pins and potential chassis for the cells.

### ISSUE THREAD

**Issue by ragnorc** [louis-threedots/louis#24]

**Comment by GregBrimble** [comment]
Angled pins?

**Comment by ragnorc** [comment]
Is curved pins a better word maybe? 😄

**Comment by GregBrimble** [comment]
You mean like those test pins we printed earlier?

**Comment by ragnorc** [comment]
I guess, the basic idea is to reduce the distance between the pins without making the disks necessarily smaller

**Comment by GregBrimble** [comment]
Gotcha 👍 will give it a think this weekend.
