### ISSUE TITLE
Add print sentence utility function.

### ISSUE THREAD

**Issue by ragnorc** [louis-threedots/louis#33]

**Comment by Canbenix** [comment]
The cells near the end of the row will not go to blank when printing the last part of the sentence.
Example:
Printing "chocolate muffins" on 7 cells ->
c   h   o   c   o   l   a
t    e   ' '   m  u   f   f
i    n   s   **m  u   f   f**
The space character corresponds to a blank output.

**Comment by Canbenix** [comment]
![image](https://user-images.githubusercontent.com/45103692/77527803-22b5b800-6e8d-11ea-9d85-e44ed84f6303.png)

This needs fixing too. Right now each individual capital letter is indicated (which I think is the correct way of doing that but I haven't checked), but also each individual digit. Instead it should be as in the screenshot (taken from https://www.pharmabraille.com/pharmaceutical-braille/the-braille-alphabet/).

**Comment by ragnorc** [comment]
Okay, will take care of that

**Comment by ragnorc** [comment]
Can be closed as #47 fixes it.
